### ISSUE TITLE
Style alternative for `agread`

### ISSUE THREAD

**Issue by paulhibbing** [bhelsel/agcounts#14]
This is just a suggestion, and I'm sure there are pros and cons of this revised approach versus the current one. But here goes: As an alternative to S3, you could consider setting up a switch, with or without the user selecting their desired parser. That could look like this:

```
agread <- function(path, verbose = FALSE, parser = c("reticulate", "GGIR", "read.gt3x"), ...){

  ## Select 'reticulate' by default unless the user specifies a different option:
  parser <- match.arg(parser)

  ## Map to the desired function (each function can start )
  switch(
    parser,
    "reticulate" = agread.pygt3x(path, verbose, ...),
    "GGIR" = agread.ggir(path, verbose, ...),
    "read.gt3x" = agread.gt3x(path, verbose, ...),
    ## All others:
    stop("No method exists yet for ", sQuote(parser), call. = FALSE)
  )

}
```

The above implementation allows the user to select which parser they want, but you could also preserve your existing logic about using `pygt3x` whenever possible. Other than that, this alternative layout may not be that different from the S3 approach. Personally, I think S3 is best for cases where there's an inherent difference in the expected data structures getting passed in, whereas here the class is just assigned to the file path as a way to get the mapping/routing right. (There is no true difference between the `pygt3x`, `ggir`, and `gt3x` classes.) That said, there are probably quite a few other factors to consider, so this is just my initial opinion. (I guess the potential use of `NextMethod` if one of them fails could be a reason to use S3, now that I think about it...)

Feel free to close, comment, or contemplate this. I just thought I would throw it out there.

**Comment by bhelsel** [comment]
Added this style alternative to agcounts v0.5.0 with an option to use the `agcalibrate` function within a piping structure with `calculate_counts`. The `agcalibrate` function uses a C++ version of the GGIR `g.calibrate` function.
