### ISSUE TITLE
Time shift by one hour/Timezone issue

### ISSUE THREAD

**Issue by clevengerkimberly** [bhelsel/agcounts#3]
Hello-
The function uses tz="America/Chicago" throughout. Not sure if this will cause issues for people in other timezones. However, I was doing a comparison of get_counts and actilife-generated counts on 66 files. For 5 of the files, the time was off by one hour. There were no changes in timezone/daylight savings for these files, so not sure what the issue was, but adding "tz="America/Chicago" at the line below solved the issue. and made the times align with actilife for all files.

```{r}
epoch_counts$time <- as.POSIXct(epoch_counts$time, origin = "1970-01-01",tz="America/Chicago")
```

**Comment by bhelsel** [comment]
Commits by @paulhibbing use `lubridate::force_tz("UTC")` in [agcounts v0.3.0](https://github.com/bhelsel/agcounts/releases/tag/v0.3.0). This should help fix this issue @clevengerkimberly, but let me know if the problem persists.
