### ISSUE TITLE
changing default for argument minloadcrit?

### ISSUE THREAD

**Issue by vincentvanhees** [bhelsel/agcounts#34]
It may be good to bring to your attention that I am changing the default argument `minloadcrit` value in GGIR from 72 to 168. See description and motivation in https://github.com/wadpac/GGIR/issues/1101

This will slow down the auto-calibration procedure but seems worth it when user wants to rely on ENMO metric. On the other hand, the results I present in that issue indicate also that for other metrics we may be fine with less than 72 hours of data or skipping the auto-calibration entirely as we already hinted at in the 2014 publication. So, it may be worth exploring whether a more clever setting of minloadcrit depending on acceleration metrics to be derived could optimise processing time without compromising the output.

**Comment by bhelsel** [comment]
Thanks Vincent! I'm making this change in the most recent version of the `agcounts` R package so it matches your updates to the `GGIR` package.
