### ISSUE TITLE
Timestamp mismatch with ActiLife

### ISSUE THREAD

**Issue by clevengerkimberly** [bhelsel/agcounts#4]
I think you're aware of this, but putting it here so other users are aware too- or if someone has time to sort out what is happening, even better! 
Some (but not all) files have one extra row compared to the ActiLife output. The time stamp starts at the correct time, but the first row of counts is not present in the Actilife file. 

For example, below you can see that both the agcounts and ActiLife start at 16:00:00, but the counts from agcounts have an extra first row (0,18,0) that, if removed, makes it align with the ActiLife data. 

**agcounts data- length = 154740**

| rownum|  Timestamp |Axis1_new| Axis2_new| Axis3_new| VM_new| id|
|----|----|------|-----|-------|--------|-----|
|1 |2021-07-07 16:00:00      |   0 |       18    |     0     |18 |12|
|2 |2021-07-07 16:00:05       |  0  |       3      |   0     | 3 |12|
|3 |2021-07-07 16:00:10        | 0   |     41      |   0     |41| 12|
|4 |2021-07-07 16:00:15        |47   |     52      |  12    | 71| 12|
|5 |2021-07-07 16:00:20         |0     |    0         |0      |0 |12|
|6 |2021-07-07 16:00:25         |0      |   0        | 0      |0 |12|

**Actilife data- length = 154739**

|rownum|Timestamp |Axis1_old |Axis2_old |Axis3_old |  VM_old| id|
|-----|----|------|-----|-------|--------|-----|
|1| 2021-07-07 16:00:00 |        0    |     3 |        0  |3 |12|
|2 |2021-07-07 16:00:05   |      0     |   41     |    0 |41 |12|
|3 |2021-07-07 16:00:10    |    47     |   52     |   12| 71 |12|
|4 |2021-07-07 16:00:15     |    0       |  0       |  0  |0 |12|
|5 |2021-07-07 16:00:20      |   0        | 0        | 0 | 0 |12|
|6 |2021-07-07 16:00:25       |  0         |0        | 0  |0 |12|

I didn't test this extensively, but using a longer epoch made the problem go away in the files I tested. For example, I've linked to two sets of files- each containing a gt3x and the 5-sec and 15-sec count files exported from ActLife. For the files labelled "NoExtraRow," there is no issue at either epoch and agcounts and ActiLife generate similar count values/same data lengths. In the files labelled "Extra Row," agcounts generates the extra row of data but only for counts per 5-sec and not counts per 15-sec.

[https://www.dropbox.com/s/d7q8cn2zpplll9s/Example.zip?dl=0](url)

**Comment by bhelsel** [comment]
@clevengerkimberly I can look into this more later, but when I try to read in the ExtraRow.gt3x with read.gt3x I get a warning message that says "duplicated time indices - usually indicative of a problem!" I've never had a .gt3x file with duplicated time indices, so I'm not entirely sure how to fix that. I'm wondering if the duplicated time indices are throwing off the algorithm. I did not get that warning message when reading in the NoExtraRow.gt3x file.

**Comment by paulhibbing** [comment]
From what I remember of working on `AGread`, there are a lot of little wacky things like this, where there's a blip in the raw data that ActiLife handles by unknown means.

My guess is the first couple of ACTIVITY/2 packets in the file had the same timestamp, and ActiLife is set up to discard the first one if this happens.

Every time I ran into something like this, I would contact Joe Nguyen at ActiGraph to confirm how the issue should be handled. He was always super helpful and timely and all around great to work with.

**Comment by bhelsel** [comment]
I think the commits from @paulhibbing helped with this issue. In [agcounts v0.3.0](https://github.com/bhelsel/agcounts/releases/tag/v0.3.0), I'm not seeing the extra row. @clevengerkimberly I'm closing this issue, but let me know if you run into the problem with other files.
