### ISSUE TITLE
[ENH] Speed up downsampling

### ISSUE THREAD

**Issue by paulhibbing** [bhelsel/agcounts#7]
It looks like `.resample` is a bottleneck for large files. I don't have my head around the code yet, but it looks like a place where `Rcpp` could help. Leaving this issue as a bookmark, knowing it will take awhile to get to.

**Comment by bhelsel** [comment]
Great idea! I've been wanting to learn some C++ but will be awhile before I'm at the level where I can implement the code. I'm definitely in support of speeding up the program if possible. Right now, it seems to be taking ~ 60 seconds per 7 day file.

**Comment by bhelsel** [comment]
@paulhibbing I got this process started by adding the Rcpp framework. I also replaced a for loop in R `.resample` function with a C++ function. I'll add more over time as I learn more Rcpp and identify more problem spots in the code, but this improvement seems to save ~0.5 seconds for a 7-day file that I used to test it.
